version: '3.7'

services:
  
  datastore:
    image: mongo
    ports:
      - 127.0.0.1:27019:27017

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"