build:
	docker build -t user-cli .
run:
	docker run -e MICRO_REGISTRY=mdns user-cli command \
		--name="Edwin Cloud" \ 
		--email="ecloud412@gmail.com" \
		--password="testing123" \
		--company="Cloud Enterprises"